name: Build

on:
  push: { branches: [main] }

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ./src/root.tex
          args: >
            -xelatex
            -file-line-error
            -halt-on-error
            -interaction=nonstopmode
            -outdir="${{ github.workspace }}/build/"
            -cd

      - name: Print workspace directory tree
        shell: bash
        run: find . -not \( -path ./.git -prune \)

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "release-${{ github.sha }}"
          name: "Release"
          body: "The compilation output from commit ${{ github.sha }}."
          files: ./build/root.pdf
